Bionemo FW v1.5 EA Release

diff --git a/internal/jet/workloads/partial-conv-trainings/recipes/config_downstream_protein.yaml b/internal/jet/workloads/partial-conv-trainings/recipes/config_downstream_protein.yaml
--- a/internal/jet/workloads/partial-conv-trainings/recipes/config_downstream_protein.yaml
+++ b/internal/jet/workloads/partial-conv-trainings/recipes/config_downstream_protein.yaml
@@ -1,7 +1,7 @@
 type: recipe
 format_version: 1
 maintainers: [dorotat]
-logger: dllogger
+loggers: [tensorboard, dllogger, extra]
 labels:
   origin: bionemo
   workload_ref: ""
@@ -47,19 +47,36 @@ spec:
     ++create_dllogger_callbacks=True ++create_trainer_metric_callback=True \
     ++dllogger_callbacks_kwargs.use_existing_dllogger=True ++dllogger_callbacks_kwargs.warmup={warmup} \
     ++dllogger_callbacks_kwargs.json_file={dllogger_file} ++trainer_metric_callback_kwargs.log_path={assets_dir} \
-    ++logs_dir={logs_dir}
-  time_limit: 3600
+    ++logs_dir={logs_dir};
+    if [ -z $SLURM_LOCALID ] || [ $SLURM_LOCALID = 0 ]
+    then
+      mkdir -p {tensorboard_dir}
+      find {assets_dir} -type f -name "events.out.tfevents*" -exec cp {{}} {tensorboard_dir} \;
+      latest_log="{assets_dir}/run_0/output_script-0.log";
+      [ ! -f "$latest_log" ] && {{ echo "File $latest_log does not exist. Exiting with error."; exit 1; }};
+      experiment_link=$(grep -o "View run at https://wandb.ai/[^']*" "$latest_log" | awk 'NR==1 {{print $4}}');
+      project_link=$(grep -o "View project at https://wandb.ai/[^']*" "$latest_log" | awk 'NR==1 {{print $4}}');
+      echo "{{WANDB_RUN_LINK: \"$experiment_link\", WANDB_PROJECT_LINK: \"$project_link\"}}" > {logs_dir}/extra.yaml
+    fi
+  time_limit: 14400
   artifacts: {}
-  metrics:
-    reduced_train_loss:
-      goal: minimize
-      tags: [primary]
-    val_loss:
-      goal: minimize
-      tags: [secondary]
-    val_3state_accuracy:
-      goal: maximize
-      tags: [secondary]
+metrics:
+  throughput_train:
+    goal: maximize
+    tags: [ performance ]
+    key: primary
+  reduced_train_loss:
+    goal: minimize
+    tags: [accuracy]
+    key: secondary
+  val_loss:
+    goal: minimize
+    tags: [accuracy]
+    key: tertiary
+  val_3state_accuracy:
+    goal: maximize
+    tags: [accuracy]
+    key: 4th
 products:
   - domain: [protein]
     nodes: [ 1 ]
@@ -72,6 +89,3 @@ products:
         batch_size: [2]
         max_epochs: [20]
         seed: [1234]
-
-
-
diff --git a/internal/jet/workloads/partial-conv-trainings/recipes/config_openfold.yaml b/internal/jet/workloads/partial-conv-trainings/recipes/config_openfold.yaml
--- a/internal/jet/workloads/partial-conv-trainings/recipes/config_openfold.yaml
+++ b/internal/jet/workloads/partial-conv-trainings/recipes/config_openfold.yaml
@@ -1,7 +1,7 @@
 type: recipe
 format_version: 1
 maintainers: [dorotat]
-logger: dllogger
+loggers: [tensorboard, dllogger, extra]
 labels:
   origin: bionemo
   workload_ref: ""
@@ -54,16 +54,32 @@ spec:
     ++create_dllogger_callbacks=True ++create_trainer_metric_callback=True \
     ++dllogger_callbacks_kwargs.use_existing_dllogger=True ++dllogger_callbacks_kwargs.warmup={warmup} \
     ++dllogger_callbacks_kwargs.json_file={dllogger_file} ++trainer_metric_callback_kwargs.log_path={assets_dir} \
-    ++logs_dir={logs_dir}
+    ++logs_dir={logs_dir};
+    if [ -z $SLURM_LOCALID ] || [ $SLURM_LOCALID = 0 ]
+    then
+      mkdir -p {tensorboard_dir}
+      find {assets_dir} -type f -name "events.out.tfevents*" -exec cp {{}} {tensorboard_dir} \;
+      latest_log="{assets_dir}/run_0/output_script-0.log";
+      [ ! -f "$latest_log" ] && {{ echo "File $latest_log does not exist. Exiting with error."; exit 1; }};
+      experiment_link=$(grep -o "View run at https://wandb.ai/[^']*" "$latest_log" | awk 'NR==1 {{print $4}}');
+      project_link=$(grep -o "View project at https://wandb.ai/[^']*" "$latest_log" | awk 'NR==1 {{print $4}}');
+      echo "{{WANDB_RUN_LINK: \"$experiment_link\", WANDB_PROJECT_LINK: \"$project_link\"}}" > {logs_dir}/extra.yaml
+    fi
   time_limit: 14400
   artifacts: {}
-  metrics:
-    train_loss_epoch:
-      goal: minimize
-      tags: [primary]
-    val_loss:
-      goal: minimize
-      tags: [secondary]
+metrics:
+  throughput_train:
+    goal: maximize
+    tags: [ performance ]
+    key: primary
+  val_lddt_ca:
+    goal: maximize
+    tags: [accuracy]
+    key: secondary
+  weighted_total_loss:
+    goal: minimize
+    tags: [accuracy]
+    key: tertiary
 products:
   - domain: [protein]
     variant: [train]
@@ -71,10 +87,8 @@ products:
     nodes: [2]
     gpus: [8]
     config_name: [openfold_initial_training]
-    max_steps: [80000]
+    max_steps: [1675]
     batch_size: [1]
     precision: [32]
     seed: [44]
     val_check_interval: [50]
-
-
